org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.176
neo_version_range=[21.1.176,21.2)
loader_version_range=[4,)

cc_tweaked_version=1.120.2
cc_tweaked_version_range=[1.120.2]

mod_id=cc_tweaked_unicode_support
mod_name=CC: Tweaked Unicode Support
mod_license=MIT AND LicenseRef-CCPL
mod_version=1.0.1
mod_group_id=ru.sanseddy.cctweakedunicodesupport
mod_authors=Sanseddy
mod_description=Adds full Unicode support to CC: Tweaked.
